SELECT PROD_ID,DATE_EXTRACTION,COMPETITOR,COMPETITOR_PRICE,PAY_TYPE,COUNT( * )
FROM sa_comp_prices
GROUP BY PROD_ID,DATE_EXTRACTION,COMPETITOR,COMPETITOR_PRICE,PAY_TYPE
HAVING COUNT( * ) > 1;

SELECT *
FROM sa_comp_prices
WHERE
	PROD_ID = 'P6' AND
    DATE_EXTRACTION = '2015-02-16 20:10:13' AND
	COMPETITOR = 'C4' AND
	COMPETITOR_PRICE = '2199' AND
	PAY_TYPE = '2';

DELETE a FROM nomes AS a, nomes AS b WHERE a.nome=b.nome AND a.id < b.id;