SELECT 
	dt.DATE,
	dp.PRODUCT,
	dc.COMPETITOR,
	dy.PAY_TYPE,
	cp.COMPETITOR_PRICE,
	cp.NUM_EXTRACTIONS,
	ROUND(MIN(cp.COMPETITOR_PRICE),2) AS MIN_UNIT_PRICE, 
	ROUND(MAX(cp.COMPETITOR_PRICE),2) AS MAX_UNIT_PRICE,
	(ROUND(MAX(cp.COMPETITOR_PRICE),2)-ROUND(MIN(cp.COMPETITOR_PRICE),2)) AS DIFF_UNIT_PRICE,
	ROUND(((MAX(cp.COMPETITOR_PRICE)/MIN(cp.COMPETITOR_PRICE))-1)*100,2) AS VAR_UNIT_PRICE,
	ROUND(AVG(cp.COMPETITOR_PRICE),2) AS AVG_PRICE
FROM 
    b2w.dw_ft_comp_prices cp INNER JOIN b2w.dw_dim_time dt
    ON cp.SK_TIME = dt.SK_TIME
    
    INNER JOIN b2w.dw_dim_prod dp
    ON cp.SK_PROD = dp.SK_PROD
    
    INNER JOIN b2w.dw_dim_comp dc
    ON cp.SK_COMPETITOR = dc.SK_COMP
    
    INNER JOIN b2w.dw_dim_pay dy
    on cp.SK_PAY = dy.SK_PAY
WHERE cp.SK_PAY = '1' AND cp.SK_PROD = '2' AND cp.SK_TIME = '1'
GROUP BY 
	dt.DATE,
	dp.PRODUCT,
	dc.COMPETITOR,
	dy.PAY_TYPE,
	cp.COMPETITOR_PRICE,
    cp.NUM_EXTRACTIONS
ORDER BY 1, 2, 3, 4;

SELECT 
	t1.PROD_ID, 
	t1.DATE_EXTRACTION, 
	t1.COMPETITOR, 
	t1.COMPETITOR_PRICE, 
	t1.PAY_TYPE
FROM b2w.ods_comp_prices t1
WHERE 
	t1.PROD_ID='P2' AND
	t1.DATE_EXTRACTION = '2015-01-01' AND
	t1.COMPETITOR = 'C1' AND
	t1.COMPETITOR_PRICE = '829' AND
	t1.PAY_TYPE = '1';