SELECT 
	t1.PROD_ID, 
	t1.DATE_EXTRACTION, 
	t1.COMPETITOR, 
	t1.COMPETITOR_PRICE, 
	t1.PAY_TYPE, 
	COUNT(*) AS QTY_EXT
FROM b2w.ods_comp_prices t1
GROUP BY t1.PROD_ID, t1.DATE_EXTRACTION, t1.COMPETITOR, t1.COMPETITOR_PRICE, t1.PAY_TYPE;

SELECT 
	t1.PROD_ID, 
	t1.DATE_EXTRACTION, 
	t1.COMPETITOR, 
	t1.COMPETITOR_PRICE, 
	t1.PAY_TYPE
FROM b2w.ods_comp_prices t1
WHERE 
	t1.PROD_ID='P1' AND
	t1.DATE_EXTRACTION = '2015-03-17' AND
	t1.COMPETITOR = 'C5' AND
	t1.COMPETITOR_PRICE = '1499' AND
	t1.PAY_TYPE = '1';

SELECT 
	t1.PROD_ID, 
	t1.DATE_EXTRACTION, 
	t1.COMPETITOR, 
	t1.COMPETITOR_PRICE, 
	t1.PAY_TYPE
FROM b2w.sa_comp_prices t1
WHERE 
	t1.PROD_ID='P1' AND
	t1.DATE_EXTRACTION LIKE '%2015-03-17%' AND
	t1.COMPETITOR = 'C5' AND
	t1.COMPETITOR_PRICE = '1499' AND
	t1.PAY_TYPE = '1';